spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_cs_demo
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false
    repair-on-migrate: true
    locations: classpath:db/migration
    
  threads:
    virtual:
      enabled: true
      
server:
  port: 8080
  
logging:
  level:
    org.flywaydb: DEBUG
    org.example.aicsdemo: DEBUG
    org.springframework: INFO 